import type { MacroIndicatorCatalogEntry } from "./types.ts";

export const SIGNAL_CLASS_WEIGHT = {
  clear: 1,
  speculative: 0.5,
} as const;

export const MACRO_INDICATOR_CATALOG: MacroIndicatorCatalogEntry[] = [
  {
    indicatorId: "debt_gdp_us",
    region: "US",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Debt / GDP (US)",
    description: "Public debt burden vs GDP.",
    inputs: ["debt_to_gdp_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.3,
  },
  {
    indicatorId: "deficit_gdp_us",
    region: "US",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Deficit / GDP (US)",
    description: "Fiscal deficit burden vs GDP.",
    inputs: ["deficit_to_gdp_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.1,
  },
  {
    indicatorId: "real_yield_10y_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Real Yield 10Y (US)",
    description: "Long-term real rate anchor.",
    inputs: ["real_yield_10y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.2,
  },
  {
    indicatorId: "nominal_yield_10y_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Nominal Yield 10Y (US)",
    description: "Nominal long-end yields.",
    inputs: ["nominal_yield_10y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "yield_curve_10y_minus_2y_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Yield Curve 10Y-2Y (US)",
    description: "Policy tightness and growth expectations.",
    inputs: ["yield_curve_10y_minus_2y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "growth",
  },
  {
    indicatorId: "core_cpi_us",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Core CPI level (US)",
    description: "Core inflation level.",
    inputs: ["core_cpi_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "core_cpi_yoy_us",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Core CPI YoY (US)",
    description: "Core inflation momentum.",
    inputs: ["core_cpi_yoy_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.2,
  },
  {
    indicatorId: "breakeven_10y_us",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "10Y Breakeven (US)",
    description: "Inflation expectation anchor.",
    inputs: ["breakeven_10y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "gold_usd",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Gold USD",
    description: "Market-based confidence proxy.",
    inputs: ["gold_usd"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.7,
    overlay: "hard_asset",
  },
  {
    indicatorId: "gold_minus_real_yield_spread",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Gold - Real Yield Spread",
    description: "Gold tailwind proxy.",
    inputs: ["gold_minus_real_yield_spread"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.1,
    overlay: "hard_asset",
  },
  {
    indicatorId: "pmi_momentum_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "speculative",
    title: "PMI Momentum",
    description: "Cyclical growth momentum signal.",
    inputs: ["pmi_momentum_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.6,
    overlay: "growth",
  },
  {
    indicatorId: "hy_spread_us",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "HY Spread US",
    description: "Credit stress proxy.",
    inputs: ["hy_spread_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "stress",
  },
];
