import type { MacroIndicatorCatalogEntry } from "./types.ts";

export const SIGNAL_CLASS_WEIGHT = {
  clear: 1,
  speculative: 0.5,
} as const;

export const MACRO_INDICATOR_CATALOG: MacroIndicatorCatalogEntry[] = [
  {
    indicatorId: "debt_gdp_us",
    region: "US",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Debt / GDP (US)",
    description: "Public debt burden vs GDP.",
    inputs: ["debt_to_gdp_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.3,
  },
  {
    indicatorId: "deficit_gdp_us",
    region: "US",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Deficit / GDP (US)",
    description: "Fiscal deficit burden vs GDP.",
    inputs: ["deficit_to_gdp_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.1,
  },

  // Added to strengthen A_FISCAL semantics: explicit debt-servicing pressure signal.
  {
    indicatorId: "interest_cost_proxy_us",
    region: "US",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Interest Cost Proxy (US)",
    description: "Debt burden multiplied by long-end nominal yield as a proxy for debt servicing pressure.",
    inputs: ["interest_cost_proxy_us"],
    transform: "spread",
    scoring: "percentile_10y",
    blockWeight: 1.1,
  },
  {
    indicatorId: "real_yield_10y_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Real Yield 10Y (US)",
    description: "Long-term real rate anchor.",
    inputs: ["real_yield_10y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.2,
  },
  {
    indicatorId: "nominal_yield_10y_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Nominal Yield 10Y (US)",
    description: "Nominal long-end yields.",
    inputs: ["nominal_yield_10y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "yield_curve_10y_minus_2y_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Yield Curve 10Y-2Y (US)",
    description: "Policy tightness and growth expectations.",
    inputs: ["yield_curve_10y_minus_2y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "growth",
  },
  {
    indicatorId: "core_cpi_us",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Core CPI level (US)",
    description: "Core inflation level.",
    inputs: ["core_cpi_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "core_cpi_yoy_us",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Core CPI YoY (US)",
    description: "Core inflation momentum.",
    inputs: ["core_cpi_yoy_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.2,
  },
  {
    indicatorId: "breakeven_10y_us",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "10Y Breakeven (US)",
    description: "Inflation expectation anchor.",
    inputs: ["breakeven_10y_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "gold_usd",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Gold USD",
    description: "Market-based confidence proxy.",
    inputs: ["gold_usd"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.7,
    overlay: "hard_asset",
  },
  {
    indicatorId: "gold_minus_real_yield_spread",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Gold - Real Yield Spread",
    description: "Gold tailwind proxy.",
    inputs: ["gold_minus_real_yield_spread"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.1,
    overlay: "hard_asset",
  },
  {
    indicatorId: "pmi_momentum_us",
    region: "US",
    block: "B_MONETARY",
    signalClass: "speculative",
    title: "PMI Momentum",
    description: "Cyclical growth momentum signal.",
    inputs: ["pmi_momentum_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.6,
    overlay: "growth",
  },
  {
    indicatorId: "hy_spread_us",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "HY Spread US",
    description: "Credit stress proxy.",
    inputs: ["hy_spread_us"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "stress",
  },
  {
    indicatorId: "oil_brent_usd",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Brent Oil (USD)",
    description: "Brent crude level.",
    inputs: ["oil_brent_usd"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "oil_yoy",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Oil YoY",
    description: "Oil price annual change.",
    inputs: ["oil_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "oil_vs_real_yield",
    region: "US",
    block: "C_INFLATION",
    signalClass: "speculative",
    title: "Oil vs Real Yield",
    description: "Oil minus 10Y real yield proxy spread.",
    inputs: ["oil_vs_real_yield"],
    transform: "spread",
    scoring: "percentile_10y",
    blockWeight: 0.7,
  },
  {
    indicatorId: "natgas_usd",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Natural Gas (USD)",
    description: "US natural gas level.",
    inputs: ["natgas_usd"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.7,
  },
  {
    indicatorId: "natgas_yoy",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Natural Gas YoY",
    description: "Natural gas annual change.",
    inputs: ["natgas_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "copper_usd",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Copper (USD)",
    description: "Copper benchmark level.",
    inputs: ["copper_usd"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "copper_yoy",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Copper YoY",
    description: "Copper annual change.",
    inputs: ["copper_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 0.9,
  },
  {
    indicatorId: "industrial_metals_index",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Industrial Metals Index",
    description: "Broad industrial metals benchmark.",
    inputs: ["industrial_metals_index"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "industrial_metals_yoy",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Industrial Metals YoY",
    description: "Industrial metals annual change.",
    inputs: ["industrial_metals_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "commodity_index",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Commodity Index",
    description: "Broad commodity price index.",
    inputs: ["commodity_index"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.7,
  },
  {
    indicatorId: "commodity_index_yoy",
    region: "US",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "Commodity Index YoY",
    description: "Commodity index annual change.",
    inputs: ["commodity_index_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 0.9,
  },
  {
    indicatorId: "fed_balance_sheet_total",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Fed Balance Sheet",
    description: "Total Federal Reserve assets.",
    inputs: ["fed_balance_sheet_total"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "hicp_inflation_ea",
    region: "EA",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "HICP Inflation (EA)",
    description: "Headline HICP inflation in the euro area.",
    inputs: ["hicp_yoy_ea"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.2,
  },
  {
    indicatorId: "hicp_momentum_ea",
    region: "EA",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "HICP Momentum (EA)",
    description: "3M inflation momentum in euro area HICP.",
    inputs: ["hicp_momentum_ea"],
    transform: "momentum",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "real_yields_ea",
    region: "EA",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Real Yields (EA)",
    description: "Euro area long-end real yields.",
    inputs: ["real_yield_10y_ea"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.1,
  },
  {
    indicatorId: "ecb_balance_sheet_ea",
    region: "EA",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "ECB Balance Sheet",
    description: "ECB consolidated balance sheet size.",
    inputs: ["ecb_balance_sheet_ea"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "m3_growth_ea",
    region: "EA",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "M3 Growth (EA)",
    description: "Euro area broad money growth proxy.",
    inputs: ["m3_growth_ea"],
    transform: "momentum",
    scoring: "percentile_10y",
    blockWeight: 0.9,
    overlay: "growth",
  },
  {
    indicatorId: "debt_gdp_ea",
    region: "EA",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Debt/GDP (EA)",
    description: "General government debt to GDP.",
    inputs: ["debt_gdp_ea"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.2,
  },
  {
    indicatorId: "deficit_gdp_ea",
    region: "EA",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Deficit/GDP (EA)",
    description: "General government deficit to GDP.",
    inputs: ["deficit_gdp_ea"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "credit_spreads_ea",
    region: "EA",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "Credit Spreads (EA)",
    description: "Euro area credit spread pressure.",
    inputs: ["credit_spreads_ea"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "stress",
  },
  {
    indicatorId: "gold_vs_real_yield_ea",
    region: "EA",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Gold vs Real Yield (EA)",
    description: "Gold relative to euro area real yields.",
    inputs: ["gold_vs_real_yield_ea"],
    transform: "spread",
    scoring: "percentile_10y",
    blockWeight: 0.9,
    overlay: "hard_asset",
  },
  {
    indicatorId: "cpi_sweden",
    region: "SE",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "CPI Sweden",
    description: "Swedish CPI level.",
    inputs: ["cpi_se"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1.1,
  },
  {
    indicatorId: "cpi_momentum_sweden",
    region: "SE",
    block: "C_INFLATION",
    signalClass: "clear",
    title: "CPI Momentum Sweden",
    description: "3M CPI momentum for Sweden.",
    inputs: ["cpi_momentum_se"],
    transform: "momentum",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "repo_rate_se",
    region: "SE",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Repo Rate (SE)",
    description: "Riksbank policy rate.",
    inputs: ["repo_rate_se"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "gov_bond_yield_10y_se",
    region: "SE",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "SE Gov Bond 10Y",
    description: "Swedish government long bond yield.",
    inputs: ["gov_bond_yield_10y_se"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.9,
  },
  {
    indicatorId: "debt_gdp_se",
    region: "SE",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Debt/GDP (SE)",
    description: "Swedish government debt burden.",
    inputs: ["debt_gdp_se"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "deficit_gdp_se",
    region: "SE",
    block: "A_FISCAL",
    signalClass: "clear",
    title: "Deficit/GDP (SE)",
    description: "Swedish fiscal deficit burden.",
    inputs: ["deficit_gdp_se"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "infl_exp_se",
    region: "SE",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "SEK Inflation Expectations",
    description: "Inflation expectation anchor in Sweden.",
    inputs: ["infl_exp_se"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 0.9,
  },
  {
    indicatorId: "credit_spreads_se",
    region: "SE",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "Credit Spreads (SE)",
    description: "Swedish credit spread pressure.",
    inputs: ["credit_spreads_se"],
    transform: "identity",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "stress",
  },
  {
    indicatorId: "fed_balance_sheet_yoy",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Fed Balance Sheet YoY",
    description: "Fed balance sheet annual change.",
    inputs: ["fed_balance_sheet_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "m2_yoy",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "M2 YoY",
    description: "M2 annual money growth.",
    inputs: ["m2_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 1,
  },
  {
    indicatorId: "m2_momentum",
    region: "US",
    block: "B_MONETARY",
    signalClass: "speculative",
    title: "M2 Momentum",
    description: "Change in M2 YoY growth.",
    inputs: ["m2_momentum"],
    transform: "yoy_change",
    scoring: "percentile_10y",
    blockWeight: 0.7,
  },
  {
    indicatorId: "real_yield_5y",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Real Yield 5Y",
    description: "5Y TIPS real yield.",
    inputs: ["real_yield_5y"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "term_premium_proxy",
    region: "US",
    block: "B_MONETARY",
    signalClass: "clear",
    title: "Term Premium Proxy",
    description: "10Y minus 3M nominal yield spread.",
    inputs: ["term_premium_proxy"],
    transform: "spread",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "growth",
  },
  {
    indicatorId: "ig_spread_us",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "IG Spread US",
    description: "US investment-grade credit spread.",
    inputs: ["ig_spread_us"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.9,
    overlay: "stress",
  },
  {
    indicatorId: "vix_index",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "VIX",
    description: "Equity volatility stress gauge.",
    inputs: ["vix_index"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.9,
    overlay: "stress",
  },
  {
    indicatorId: "financial_conditions_index",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "Financial Conditions Index",
    description: "Broad financial stress index.",
    inputs: ["financial_conditions_index"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 1,
    overlay: "stress",
  },
  {
    indicatorId: "usd_broad_index",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "clear",
    title: "USD Broad Index",
    description: "Trade-weighted US dollar index.",
    inputs: ["usd_broad_index"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.8,
  },
  {
    indicatorId: "usd_yoy",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "USD YoY",
    description: "USD broad index annual change.",
    inputs: ["usd_yoy"],
    transform: "yoy",
    scoring: "percentile_10y",
    blockWeight: 0.7,
  },
  // backlog/unavailable: supply_chain_pressure and supply_chain_pressure_yoy are temporarily disabled for US
  // until a verified, stable source-series mapping is available in the current ingest provider set.
  {
    indicatorId: "silver_usd",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Silver USD",
    description: "Silver spot in USD.",
    inputs: ["silver_usd"],
    transform: "level",
    scoring: "percentile_10y",
    blockWeight: 0.6,
    overlay: "hard_asset",
  },
  {
    indicatorId: "gold_silver_ratio",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Gold / Silver Ratio",
    description: "Precious-metal relative value signal.",
    inputs: ["gold_silver_ratio"],
    transform: "ratio",
    scoring: "percentile_10y",
    blockWeight: 0.7,
    overlay: "hard_asset",
  },
  {
    indicatorId: "industrial_metals_vs_gold",
    region: "US",
    block: "D_CREDIBILITY",
    signalClass: "speculative",
    title: "Industrial Metals / Gold",
    description: "Cyclical metals vs defensive gold ratio.",
    inputs: ["industrial_metals_vs_gold"],
    transform: "ratio",
    scoring: "percentile_10y",
    blockWeight: 0.8,
    overlay: "hard_asset",
  },

];
