import { query } from '../../../../api/_db.ts';
import { loadProjectsForSymbol } from '../../api/loadProjectsForSymbol.ts';
import { aggregateProjectsCorporateV1 } from '../../corporate/aggregateProjects.ts';
import type { CorporateProjectEngineSnapshot } from '../../corporate/types.ts';
import { computeProjectEngineFullProductionV1 } from '../../project/engineFullProductionV1.ts';
import { computeProjectPhase2 } from '../../project/phase2.ts';
import { parseProjectJsonV1 } from '../../project/jsonv1/parse.ts';
import { resolveProjectPricesToEngineInput } from '../../project/jsonv1/resolvePrices.ts';
import { readHistoryRowsInRange } from '../../prices/db/readHistory.ts';
import type { PriceKey } from '../../prices/keys.ts';
import { analyzeRecentSustainedLows } from '../recentSustainedLow.ts';

const WINDOWS = [4,5,6] as const;
const LOOKBACKS = [6,7,8] as const;
const LOW_COUNTS = [3,4] as const;
const DISCOUNTS = [0.09,0.10,0.11] as const;
const ROLLING_MONTHS = 6, SEPARATION_MONTHS = 12;
type Tier = 'T1'|'T2'|'T3'|'FAIL';
type Params = { window:number; lookback:number; lowCount:number; discount:number };
type Prepared = { projectId:string; rawJson:unknown; physical:any; baseInput:any; baseOutput:any; productionStartYear:number; constructionStartYear:number };
type Eval = { symbol:string; projectCount:number; beta:number; stressIrr:number|null; stressNpv:number; revenueRetention:number };

const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const clone=<T>(v:T):T=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v)) as T;
function dateYearsAgo(to:string,n:number){const d=new Date(`${to}T00:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()-n);return d.toISOString().slice(0,10)}
function scalar(s:Array<number|null>|undefined){if(!Array.isArray(s))return null;const a=s.filter((v):v is number=>finite(v)&&v>0);if(!a.length)return null;const f=a[0],tol=Math.max(1e-9,Math.abs(f)*1e-9);return a.every(v=>Math.abs(v-f)<=tol)?f:null}
function lastProd(payable:Record<string,Array<number|null>>,fallback:number){let last=-1;for(const s of Object.values(payable))for(let t=0;t<s.length;t++)if(finite(s[t])&&(s[t] as number)>0)last=Math.max(last,t);return last>=0?last:fallback}
function firstConstruction(capex:Array<number|null>,tp:number){for(let t=0;t<=tp;t++)if(finite(capex[t])&&Math.abs(capex[t] as number)>1e-6)return t;return tp}
function revenue(gross:Array<number|null>,credits:Array<number|null>|null|undefined,a:number,b:number){let x=0;for(let t=a;t<=b;t++){if(!finite(gross[t]))return null;const c=credits?.[t];if(c!=null&&!finite(c))return null;x+=(gross[t] as number)+(finite(c)?c:0)}return x}
function pct(a:number[],p:number){if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?s[l]:s[l]+(s[h]-s[l])*(i-l)}

const historyCache=new Map<string,Awaited<ReturnType<typeof readHistoryRowsInRange>>>();
const stressCache=new Map<string,number|null>();
async function stressPrice(key:string,lookback:number,lowCount:number){const ck=`${key}|${lookback}|${lowCount}`;if(stressCache.has(ck))return stressCache.get(ck)??null;const to=new Date().toISOString().slice(0,10),from=dateYearsAgo(to,8),hk=`${key}|${from}|${to}`;let h=historyCache.get(hk);try{if(!h){h=await readHistoryRowsInRange({priceKey:key as PriceKey,from,to});historyCache.set(hk,h)}const a=analyzeRecentSustainedLows(h.rows,{lookbackYears:lookback,rollingMonths:ROLLING_MONTHS,minimumSeparationMonths:SEPARATION_MONTHS,selectedLowCount:lowCount});const v=a.status==='COMPUTABLE'&&finite(a.stressPrice)?a.stressPrice:null;stressCache.set(ck,v);return v}catch{stressCache.set(ck,null);return null}}

const preparedCache=new Map<string,Prepared[]|null>();
async function prepare(symbol:string):Promise<Prepared[]|null>{if(preparedCache.has(symbol))return preparedCache.get(symbol)??null;try{const loaded=await loadProjectsForSymbol(symbol);if(!loaded.length){preparedCache.set(symbol,null);return null}const out:Prepared[]=[];for(const p of loaded){const parsed=parseProjectJsonV1(p.rawJson),physical=parsed.engineInputWithoutPrices;const baseInput=await resolveProjectPricesToEngineInput({parsed,scenario:{mode:'spot'},allowRefresh:false,projectId:p.projectId});const baseOutput=computeProjectEngineFullProductionV1(baseInput);const tp=physical.productionStartPeriod,ct=firstConstruction(baseOutput.capexUSD_used,tp);out.push({projectId:p.projectId,rawJson:p.rawJson,physical,baseInput,baseOutput,productionStartYear:physical.yearsByPeriod[tp],constructionStartYear:physical.yearsByPeriod[ct]})}preparedCache.set(symbol,out);return out}catch{preparedCache.set(symbol,null);return null}}

function snap(input:any,out:any):CorporateProjectEngineSnapshot{return{capexUSD:out.capexUSD_used,fcffUSD:out.phase1.fcffUSD,grossRevenueUSD:out.revenue.grossRevenueUSD,auPriceUSDPerOz:input.aisc.auPriceUSDPerOz,priceUSDByMetal:input.spotPriceUSDByMetal,priceKeyByMetal:input.priceKeyByMetal,sustainingCostUSD:out.phase1.sustainingCostUSD,payableAuEqOz:out.aisc.payableAuEqOz}}
async function corp(ps:Prepared[],runs:Array<{input:any;output:any}>,discount:number){const byId=new Map(ps.map((p,i)=>[p.projectId,snap(runs[i].input,runs[i].output)]));return aggregateProjectsCorporateV1({discountRate:discount,projects:ps.map(p=>({projectId:p.projectId,rawJson:p.rawJson}))},{projectToSeries:async({projectId})=>{const s=byId.get(projectId);if(!s)throw new Error('missing snapshot');return s}})}
function phase(years:number[],fcff:Array<number|null>,prodYear:number,startYear:number,discount:number){const start=years.findIndex(y=>y>=startYear);if(start<0)return null;const f=fcff.slice(start),ys=years.slice(start);if(f.some(v=>v===null))return null;const tp0=ys.findIndex(y=>y>=prodYear),tp=tp0>=0?tp0:0;const o=computeProjectPhase2({masterN:f.length-1,productionStartPeriod:tp,discountRate:discount,fcffUSD:f});return finite(o.npvToday_USD)?{npv:o.npvToday_USD,irr:finite(o.irr)?o.irr:null}:null}

async function evaluate(symbol:string,p:Params):Promise<Eval|null>{const ps=await prepare(symbol);if(!ps)return null;let baseRev=0,stressRev=0;const baseRuns=ps.map(x=>({input:x.baseInput,output:x.baseOutput})),stressRuns:Array<{input:any;output:any}>=[];for(const x of ps){const input=clone(x.baseInput),from=x.physical.productionStartPeriod,to=Math.min(lastProd(x.physical.payableQtyByMetal,from),from+p.window-1);for(const [metal,series] of Object.entries(input.spotPriceUSDByMetal as Record<string,Array<number|null>>)){const key=x.physical.priceKeyByMetal[metal];if(!key)return null;const spot=scalar(x.baseInput.spotPriceUSDByMetal[metal]),low=await stressPrice(key,p.lookback,p.lowCount);if(!finite(spot)||!finite(low))return null;const m=Math.min(spot,low)/spot;for(let t=from;t<=to;t++)if(finite(series[t]))series[t]=(series[t] as number)*m;const keyed=input.priceSeriesByKey?.[key];if(keyed)for(let t=from;t<=to;t++)if(finite(keyed[t]))keyed[t]=(keyed[t] as number)*m;if(metal==='Au')for(let t=from;t<=to;t++)if(finite(input.aisc.auPriceUSDPerOz[t]))input.aisc.auPriceUSDPerOz[t]=(input.aisc.auPriceUSDPerOz[t] as number)*m}const output=computeProjectEngineFullProductionV1(input),br=revenue(x.baseOutput.revenue.grossRevenueUSD,x.baseInput.phase1.byproductCreditsUSD,from,to),sr=revenue(output.revenue.grossRevenueUSD,input.phase1.byproductCreditsUSD,from,to);if(!finite(br)||!finite(sr)||!(br>0))return null;baseRev+=br;stressRev+=sr;stressRuns.push({input,output})}const bc=await corp(ps,baseRuns,p.discount),sc=await corp(ps,stressRuns,p.discount),years=bc.corporateYearsByPeriod;if(JSON.stringify(years)!==JSON.stringify(sc.corporateYearsByPeriod))return null;const anchor=Math.min(...ps.map(x=>x.constructionStartYear)),prod=Math.min(...ps.map(x=>x.productionStartYear));const b=phase(years,bc.fcffUSD_total,prod,anchor,p.discount),s=phase(years,sc.fcffUSD_total,prod,anchor,p.discount);if(!b||!s||!(b.npv>0))return null;const rr=stressRev/baseRev,rd=1-rr,ret=s.npv/b.npv;return{symbol,projectCount:ps.length,beta:rd>1e-9?(1-ret)/rd:NaN,stressIrr:s.irr,stressNpv:s.npv,revenueRetention:rr}}

function tier(r:Eval,survival:Eval|undefined,t1=.85,t2=1.15):Tier{if(!survival||!(survival.stressNpv>0))return'FAIL';if(!finite(r.beta)||!finite(r.stressIrr))return'FAIL';if(r.beta<=t1)return'T1';if(r.beta<=t2)return'T2';return'T3'}

(async()=>{const q=await query(`SELECT DISTINCT UPPER(symbol) AS symbol FROM company_projects ORDER BY UPPER(symbol)`) as Array<{symbol?:string}>;const symbols=q.map(x=>String(x.symbol??'').trim().toUpperCase()).filter(Boolean);const combos:Params[]=[];for(const window of WINDOWS)for(const lookback of LOOKBACKS)for(const lowCount of LOW_COUNTS)for(const discount of DISCOUNTS)combos.push({window,lookback,lowCount,discount});const results=new Map<string,Map<string,Eval>>();console.log(`CYCLE_STABILITY_BEGIN combos=${combos.length} symbols=${symbols.length}`);
for(const p of combos){const key=`w${p.window}_h${p.lookback}_l${p.lowCount}_d${Math.round(p.discount*100)}`,m=new Map<string,Eval>();for(const s of symbols){const r=await evaluate(s,p);if(r)m.set(s,r)}results.set(key,m);const bs=[...m.values()].map(r=>r.beta).filter(finite);console.log(`CYCLE_STABILITY_COMBO ${key} n=${m.size} betaP25=${pct(bs,.25)?.toFixed(3)} betaP50=${pct(bs,.5)?.toFixed(3)} betaP75=${pct(bs,.75)?.toFixed(3)}`)}
const survivalKey='w6_h7_l3_d10',survival=results.get(survivalKey)??new Map<string,Eval>();for(const s of symbols){const counts:Record<Tier,number>={T1:0,T2:0,T3:0,FAIL:0};const betas:number[]=[];let available=0;for(const m of results.values()){const r=m.get(s);if(!r)continue;available++;betas.push(r.beta);counts[tier(r,survival.get(s))]++}const denom=available||1;const modal=(Object.entries(counts) as Array<[Tier,number]>).sort((a,b)=>b[1]-a[1])[0];console.log(`CYCLE_STABILITY_SYMBOL ${s} projects=${preparedCache.get(s)?.length??0} available=${available}/${combos.length} T1=${counts.T1} T2=${counts.T2} T3=${counts.T3} FAIL=${counts.FAIL} t1Share=${(counts.T1/denom).toFixed(3)} modal=${modal[0]} modalShare=${(modal[1]/denom).toFixed(3)} betaMin=${betas.length?Math.min(...betas).toFixed(3):'null'} betaMedian=${pct(betas,.5)?.toFixed(3)??'null'} betaMax=${betas.length?Math.max(...betas).toFixed(3):'null'}`)}
for(const [t1,t2] of [[.80,1.10],[.85,1.15],[.90,1.20]] as const){const base=results.get('w5_h7_l3_d10')??new Map<string,Eval>(),c:Record<Tier,number>={T1:0,T2:0,T3:0,FAIL:0},mem:Record<Tier,string[]>={T1:[],T2:[],T3:[],FAIL:[]};for(const [s,r] of base){const z=tier(r,survival.get(s),t1,t2);c[z]++;mem[z].push(s)}console.log(`CYCLE_STABILITY_THRESHOLD ${t1.toFixed(2)}_${t2.toFixed(2)} T1=${c.T1}[${mem.T1}] T2=${c.T2}[${mem.T2}] T3=${c.T3}[${mem.T3}] FAIL=${c.FAIL}[${mem.FAIL}]`)}console.log('CYCLE_STABILITY_END');console.log('cycleStabilityGridDiagnostic.test.ts passed')})().catch(e=>{console.error(e);process.exitCode=1});