import type { ScreeningFieldDef } from "./types.ts";

const NUMERIC_OPS = [">", ">=", "<", "<=", "==", "!="] as const;
const CATEGORICAL_OPS = ["==", "!=", "in"] as const;

export const SCREENING_FIELDS: ScreeningFieldDef[] = [
  { key: "return_5d", label: "Return 5D", group: "price", dataType: "number", unit: "percent", inputKind: "percent_like", valueFormatHint: "Ange procenttal, t.ex. 8 för +8%.", allowedOperators: [...NUMERIC_OPS], source: "price_screen_snapshot", simple: true, advanced: true, description: "Prisförändring över 5 handelsdagar.", interpretation: "20 betyder +20% avkastning på 5 dagar.", example: "Sätt > 10 för att hitta aktier upp minst 10% på 5 dagar." },
  { key: "return_20d", label: "Return 20D", group: "price", dataType: "number", unit: "percent", inputKind: "percent_like", valueFormatHint: "Ange procenttal, t.ex. 5 för +5%.", allowedOperators: [...NUMERIC_OPS], source: "price_screen_snapshot", simple: true, advanced: true, description: "Prisförändring över 20 handelsdagar.", interpretation: "20 betyder +20% avkastning på 20 dagar.", example: "Sätt > 5 för att hitta aktier upp minst 5% senaste månaden." },
  { key: "return_60d", label: "Return 60D", group: "price", dataType: "number", unit: "percent", inputKind: "percent_like", valueFormatHint: "Ange procenttal, t.ex. 15 för +15%.", allowedOperators: [...NUMERIC_OPS], source: "price_screen_snapshot", simple: true, advanced: true, description: "Prisförändring över 60 handelsdagar.", interpretation: "20 betyder +20% avkastning på 60 dagar.", example: "Sätt > 0 för positiv 60-dagars trend." },
  { key: "drawdown_20d", label: "Drawdown 20D", group: "price", dataType: "number", unit: "percent", inputKind: "percent_like", valueFormatHint: "Ange nedgång i procentenheter, t.ex. 20 för -20% från 20D-high.", allowedOperators: [...NUMERIC_OPS], source: "price_screen_snapshot", simple: true, advanced: true, description: "Price decline from highest price over last 20 trading days.", interpretation: "20 means price is down 20% from recent high.", example: "Sätt >= 20 för att hitta aktier minst 20% under 20D-high." },
  { key: "drawdown_60d", label: "Drawdown 60D", group: "price", dataType: "number", unit: "percent", inputKind: "percent_like", valueFormatHint: "Ange nedgång i procentenheter.", allowedOperators: [...NUMERIC_OPS], source: "price_screen_snapshot", simple: true, advanced: true, description: "Price decline from highest price over last 60 trading days.", interpretation: "20 means price is down 20% from recent high.", example: "Sätt >= 25 för tydlig selloff." },
  { key: "drawdown_252d", label: "Drawdown 252D (future)", group: "price", dataType: "number", unit: "percent", inputKind: "percent_like", valueFormatHint: "Ange nedgång i procentenheter.", allowedOperators: [...NUMERIC_OPS], source: "future_cycle_snapshot", simple: false, advanced: true, description: "Price decline from 52-week high.", interpretation: "20 means price is down 20% from yearly high.", example: "Sätt >= 30 för djupare drawdown över längre fönster." },
  { key: "trend_state", label: "Trend state", group: "price", dataType: "string", unit: "state", inputKind: "categorical", enumValues: ["up", "sideways", "down"], allowedOperators: [...CATEGORICAL_OPS], source: "price_screen_snapshot", simple: true, advanced: true, description: "Förenklad trendklass: up/down/sideways.", interpretation: "in up,sideways matchar båda tillstånden.", example: "Använd == up för trendföljande screening." },
  { key: "recovery_state", label: "Recovery state", group: "price", dataType: "string", unit: "state", inputKind: "categorical", enumValues: ["selloff", "stabilizing", "early_reversal", "near_highs"], allowedOperators: [...CATEGORICAL_OPS], source: "price_screen_snapshot", simple: true, advanced: true, description: "Fas efter drawdown: selloff/stabilizing/early_reversal/near_highs.", interpretation: "in stabilizing,early_reversal fångar återhämtningsfas.", example: "Använd == near_highs för momentum nära toppar." },

  { key: "revenue_growth", label: "Revenue growth", group: "fundamentals", dataType: "number", unit: "percent", inputKind: "percent_like", allowedOperators: [...NUMERIC_OPS], source: "company income", simple: false, advanced: true },
  { key: "ebit_growth", label: "EBITDA growth", group: "fundamentals", dataType: "number", unit: "percent", inputKind: "percent_like", allowedOperators: [...NUMERIC_OPS], source: "company income", simple: false, advanced: true },
  { key: "net_income_growth", label: "Net income growth", group: "fundamentals", dataType: "number", unit: "percent", inputKind: "percent_like", allowedOperators: [...NUMERIC_OPS], source: "company income", simple: true, advanced: true },
  { key: "operating_cash_flow", label: "Operating cash flow", group: "fundamentals", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "company cashflow", simple: true, advanced: true },
  { key: "free_cash_flow", label: "Free cash flow", group: "fundamentals", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "company cashflow", simple: true, advanced: true },

  { key: "debt_to_equity", label: "Debt to equity", group: "risk", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange multipel (x), t.ex. 0.8.", allowedOperators: [...NUMERIC_OPS], source: "company balance", simple: true, advanced: true },
  { key: "net_cash_flag", label: "Net cash flag", group: "risk", dataType: "boolean", unit: "state", inputKind: "categorical", enumValues: ["true", "false"], allowedOperators: ["==", "!="], source: "company balance", simple: false, advanced: true },
  { key: "current_ratio", label: "Current ratio", group: "risk", dataType: "number", unit: "ratio", inputKind: "ratio", allowedOperators: [...NUMERIC_OPS], source: "company balance", simple: false, advanced: true },
  { key: "dilution", label: "Dilution", group: "risk", dataType: "number", unit: "percent", inputKind: "percent_like", allowedOperators: [...NUMERIC_OPS], source: "company income", simple: false, advanced: true },
  { key: "runway_months", label: "Runway months", group: "risk", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "company cash/burn", simple: true, advanced: true },

  { key: "project_npv", label: "Project NPV (future)", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "future project snapshot", simple: false, advanced: true },
  { key: "nav", label: "NAV (future)", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "future project snapshot", simple: false, advanced: true },
  { key: "ev_over_npv", label: "EV/NPV (future)", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", allowedOperators: [...NUMERIC_OPS], source: "future project snapshot", simple: false, advanced: true },

  { key: "corp_npv", label: "CORPORATE • NPV", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true, description: "Enterprise-baserad NPV från corporate snapshot.", interpretation: "Jämförs mot EV-baserade multiplar.", example: "NPV > 0 filtrerar bort bolag utan positivt enterprise-värde." },
  { key: "corp_dcf", label: "CORPORATE • DCF", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_nav", label: "CORPORATE • NAV", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_npv_per_share", label: "CORPORATE • NPV per share", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_dcf_per_share", label: "CORPORATE • DCF per share", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_nav_per_share", label: "CORPORATE • NAV per share", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_ev", label: "CORPORATE • EV", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_market_cap", label: "CORPORATE • Market Cap", group: "mining", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_ev_over_npv", label: "CORPORATE • EV/NPV", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (0.3 = 30%).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true, description: "Enterprise value dividerat med enterprise NPV.", interpretation: "0.3 betyder EV är 30% av NPV.", example: "Använd < 0.3 för djup EV-rabatt." },
  { key: "corp_ev_over_nav", label: "CORPORATE • EV/NAV", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (0.5 = 50%).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_p_over_nav", label: "CORPORATE • P/NAV", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (0.5 = 50%).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_market_cap_over_npv", label: "CORPORATE • Market Cap / NPV", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (0.1 = 10%).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_market_cap_over_nav", label: "CORPORATE • Market Cap / NAV", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (0.1 = 10%).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_cash_over_market_cap", label: "CORPORATE • Cash / Market Cap", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (0.25 = 25%).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true, description: "Reported cash från bolagets balansräkning dividerat med market cap (från corporate snapshot eller bolagsprofil).", interpretation: "0.25 betyder cash motsvarar 25% av market cap.", example: "Använd >= 0.25 för bolag där cash utgör minst 25% av börsvärdet." },
  { key: "corp_price_over_dcf_per_share", label: "CORPORATE • Price / DCF per share", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (1.0 = pris lika med DCF/aktie).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },
  { key: "corp_price_over_nav_per_share", label: "CORPORATE • Price / NAV per share", group: "mining", dataType: "number", unit: "ratio", inputKind: "ratio", valueFormatHint: "Ange decimal (1.0 = pris lika med NAV/aktie).", allowedOperators: [...NUMERIC_OPS], source: "corporate_snapshot", simple: false, advanced: true },

  { key: "founderFlag", label: "Founder flag", group: "manual", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "manual overrides", simple: true, advanced: true },
  { key: "insiderScore", label: "Insider score", group: "manual", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "manual overrides", simple: true, advanced: true },
  { key: "reratingFlag", label: "Rerating flag", group: "manual", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "manual overrides", simple: true, advanced: true },
  { key: "jurisdictionFlag", label: "Jurisdiction flag", group: "manual", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "manual overrides", simple: false, advanced: true },
  { key: "managementFlag", label: "Management flag", group: "manual", dataType: "number", unit: "absolute", inputKind: "numeric", allowedOperators: [...NUMERIC_OPS], source: "manual overrides", simple: false, advanced: true },
];

export const SCREENING_FIELD_MAP = new Map(SCREENING_FIELDS.map((field) => [field.key, field]));
